/** Operational Ledger design reminder: shared allocations are one deliberate workflow, with weights and budget consequences visible together. */
import { Link2, Split } from "lucide-react";
import { SharedActivityEditor } from "@/components/ActivityEditor";
import { useWorkspace } from "@/contexts/WorkspaceContext";

export default function SharedActivitiesPage() {
  const { activeCountryId, countries, activities, brands } = useWorkspace();
  const country = countries.find((item) => item.id === activeCountryId);
  const grouped = Object.values(activities.filter((activity) => activity.countryId === activeCountryId && activity.source === "shared").reduce<Record<string, typeof activities>>((result, activity) => ({ ...result, [activity.sharedGroupId ?? activity.id]: [...(result[activity.sharedGroupId ?? activity.id] ?? []), activity] }), {}));
  return <div className="page shared-page"><section className="page-intro shared-intro"><div><p className="eyebrow">Weighted allocation</p><h1>Shared activities, <span>settled before they reach the sheet.</span></h1><p className="page-lead">Enter one shared activity, assign brand weights that total 100%, and create budget-charged AP27 rows for {country?.name ?? "the selected country"}.</p></div><div className="shared-art"><img src="/manus-storage/action-plan-shared-allocation-art_d51a6389.png" alt="Abstract branching allocation artwork" /></div></section><SharedActivityEditor /><section className="panel shared-history"><div className="panel-heading"><div><p className="eyebrow">Allocation register</p><h2>Submitted shared activities</h2></div><span className="panel-note">{grouped.length} grouped activities</span></div>{grouped.length ? <div className="shared-group-list">{grouped.map((group) => <article key={group[0].sharedGroupId} className="shared-group"><div className="shared-group-title"><span className="glyph-icon"><Split size={17} /></span><div><strong>{group[0].activity}</strong><small>{group[0].date || "No date"} · {group[0].location || "No location"}</small></div></div><div className="allocation-chips">{group.map((row) => <span key={row.id}>{brands.find((brand) => brand.id === row.brandId)?.name ?? "Brand"} <b>{row.sharedWeight}%</b></span>)}</div><strong className="group-total">{group.reduce((sum, row) => sum + row.totalCost, 0).toLocaleString(undefined, { maximumFractionDigits: 2 })}</strong></article>)}</div> : <div className="empty-panel"><Link2 size={25} /><p>No shared activities have been submitted for this country.</p><span>Create one above to see the allocation register here.</span></div>}</section></div>;
}
